print(head(customers))
print(ggplot(customers, aes(x=CUSTOMER_STATE,y=CUSTOMER_ID)) + geom_point(aes(color=as.factor(CUSTOMER_LAST_NAME))))
print(head(items))
print(ggplot(items, aes(x=ARTIST)) + geom_histogram())
print(head(orders))
print(ggplot(orders, aes(x=as.Date(ORDER_DATE, "%Y-%m-%d"),y=as.Date(SHIPPED_DATE, "%Y-%m-%d"))) + geom_point())
print(head(order_details))
print(ggplot(order_details, aes(x=ITEM_ID)) + geom_histogram())
print(ggplot(df,aes(x=as.Date(ORDER_DATE, "%Y-%m-%d"), y=as.Date(SHIPPED_DATE, "%Y-%m-%d"), color=as.factor(UNIT_PRICE))) + geom_point() + facet_wrap(~CUSTOMER_STATE))
print(ggplot(df,aes(x=as.Date(ORDER_DATE, "%Y-%m-%d"), y=as.Date(SHIPPED_DATE, "%Y-%m-%d"), color=as.factor(TITLE))) + geom_point() + facet_wrap(~CUSTOMER_STATE)) 
print(ggplot(df,aes(x=as.Date(ORDER_DATE, "%Y-%m-%d"), y=as.Date(SHIPPED_DATE, "%Y-%m-%d"), color=as.factor(ARTIST))) + geom_point() + facet_wrap(~CUSTOMER_STATE))
